development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: app_development
  pool: 5
  username: root
  password: kobakai0707
  host: db

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: app_test
  pool: 5
  username: root
  password: kobakai0707
  host: db

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: app_production
  pool: 5
  username: root
  password: kobakai0707
  host: db